### ISSUE TITLE
How can I change batch_size?

### ISSUE THREAD

**Issue by a4152684** [fuxiao0719/PanopticNeRF#7]
When I change the "batch_size" under "panopticnerf_test.yaml"——"train", an error occured.

Traceback (most recent call last):
  File "train_net.py", line 95, in <module>
    main()
  File "train_net.py", line 92, in main
    train(cfg, network)
  File "train_net.py", line 47, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/root/data1/PanopticNeRF/lib/train/trainers/trainer.py", line 58, in train
    for iteration, batch in enumerate(data_loader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 74, in <listcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
KeyError: 89

Could you please look at this problem?

**Comment by fuxiao0719** [comment]
Hi, as ours is scene-specific settings, we only need to set the batch size to 1 here, where a larger batch size is aimed at cross-scene tasks. If your GPU storage is sufficient, you could increase the GPU-util via enlarging 'N_rays'.
